import React from 'react';
import { motion } from 'framer-motion';
import GlassCard from '../common/GlassCard';
import useLanguage from '../../hooks/useLanguage';

/**
 * 📜 TarotExplanation
 * Shows the detailed interpretation text generated by AI.
 */
const TarotExplanation = ({ card, text }) => {
  const { t } = useLanguage();

  return (
    <div className="flex-1 overflow-y-auto no-scrollbar pb-6 mt-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="space-y-4"
      >
        <h3 className="text-lg font-semibold text-white/90 sticky top-0 bg-cosmic-900/95 backdrop-blur py-2 z-10 border-b border-white/5">
          {t('tarot.interpretation')}
        </h3>

        {/* Using Markdown-like splitting for paragraphs */}
        {text.split('\n').map((para, i) => {
          if (!para.trim()) return null;
          return (
            <p key={i} className="text-gray-300 leading-relaxed text-sm">
              {para}
            </p>
          );
        })}

        {/* Card Keywords Summary */}
        <GlassCard className="mt-6 p-4 bg-white/5">
          <h4 className="text-xs font-bold text-gray-500 uppercase mb-2">
            Card Energy
          </h4>
          <div className="flex flex-wrap gap-2">
            {/* Mock Keywords based on card logic or just static "Mystical" ones for now */}
            {['Reflection', 'Destiny', 'Insight'].map(kw => (
              <span key={kw} className="px-3 py-1 bg-black/30 rounded-full text-xs text-accent-cyan border border-accent-cyan/20">
                {kw}
              </span>
            ))}
          </div>
        </GlassCard>

      </motion.div>
    </div>
  );
};

export default TarotExplanation;
